### ISSUE TITLE
a base32 bug

### ISSUE THREAD

**Issue by Nixiabing** [mufeedvh/basecrack#12]
[-] Encoded Base: MZWGCZ33GQZTQMTEM5SGMMTEPU=====

[!] Not a valid encoding.

**Comment by mufeedvh** [comment]
Hey @Nixiabing, first of all sorry for the late response. :raised_hands: 

Thank you for raising this issue, the bug was that the inbuilt `base32` charset in Python doesn't follow this charset spec and will result in an `Incorrect padding` error. A fix (https://github.com/mufeedvh/basecrack/commit/86f8ec7a713e269be116a9063a19f307222e1d6d) has been applied with the implementation of `RFC 3548` charset where the padding is stripped while decoding for handling both cases. :+1: 

![Screenshot from 2021-06-17 07-09-44](https://user-images.githubusercontent.com/26198477/122317388-165ac680-cf3b-11eb-9f9a-03a65507b0b1.png)

Again, thank you raising this issue. :heart::raised_hands:

**Comment by Nixiabing** [comment]
Thank you~
