### ISSUE TITLE
Not a valid encoding

### ISSUE THREAD

**Issue by jepunband** [mufeedvh/basecrack#3]
hi i cannot seem to get it to work ... it keeps saying not valid encoding .

[>] Enter Encoded Base: b6e6e5056e045a83e2828de658ccd5c1
[!] Not a valid encoding.

**Comment by bee-san** [comment]
Hey, that doesn't look like a base decoding to me. More like a hash. Neither Basecrack nor Cyberchef's Magic can get it:
https://gchq.github.io/CyberChef/#recipe=Magic(3,true,false,'')&input=YjZlNmU1MDU2ZTA0NWE4M2UyODI4ZGU2NThjY2Q1YzE

I think it's a hash, using `hashid` it returns:

```
➜ hashid b6e6e5056e045a83e2828de658ccd5c1
Analyzing 'b6e6e5056e045a83e2828de658ccd5c1'
[+] MD2
[+] MD5
[+] MD4
[+] Double MD5
[+] LM
[+] RIPEMD-128
[+] Haval-128
[+] Tiger-128
[+] Skein-256(128)
[+] Skein-512(128)
[+] Lotus Notes/Domino 5
[+] Skype
[+] Snefru-128
[+] NTLM
[+] Domain Cached Credentials
[+] Domain Cached Credentials 2
[+] DNSSEC(NSEC3)
[+] RAdmin v2.x
```

**Comment by jepunband** [comment]
hi @bee-san , oh ok. may i know if this tool can detect or identify what encryption is used and can it decrypt it as well?

**Comment by bee-san** [comment]
> hi @bee-san , oh ok. may i know if this tool can detect or identify what encryption is used and can it decrypt it as well?

Hey,

I am not the author of this tool and I am not going to disrespect the author of this tool by advertising my own stuff :smile:

**Comment by mufeedvh** [comment]
Hey @jepunband @bee-san, first of all, I am really sorry for the late response, this issue was buried in my notifications. :(

@jepunband, this tool is only intended to be used for **Base** encoding schemes and not for ciphers or encrypted hashes. For that, there are plenty of other great tools.

I will link @bee-san's project myself because it's pretty neat :smiley: - [**Ciphey**](https://github.com/Ciphey/Ciphey)!

Thank You! :heart::raised_hands:
