### ISSUE TITLE
python basecrack.py

### ISSUE THREAD

**Issue by N0o01** [mufeedvh/basecrack#5]
C:\python3.8\basecrack\basecrack>python basecrack.py
Traceback (most recent call last):
  File "basecrack.py", line 18, in <module>
    import base36
ModuleNotFoundError: No module named 'base36
------------------------------------------------------------------翻译
最近一次调用（回溯）：

“文件”basecrack.py“，第18行，输入<module>

导入base36

ModuleNotFoundError:没有名为“base36”的模块 

这里什么意思........没有base36的模块

**Comment by mufeedvh** [comment]
Hey @Xu1Z, first of all, I am really sorry for the late response, this issue was buried in my notifications. :(

You have to install the dependencies, you can do this with:

```
pip install -r requirements.txt
```

If you're using `Python3`, make sure you're installing with `pip3`.

I hope this was the issue, if this issue still persists please leave a comment with the commands you did and your setup.

Thank You for raising this issue! :heart::raised_hands:
